language: rust

os:
- osx
- linux

rust:
- 1.34.0
- stable
- beta
- nightly

branches:
  except:
    - gh-pages

env:
  - ONIG_FEATURES=generate

install: |
  if [ "$TRAVIS_OS_NAME" == "linux" ]
  then
    echo installing libclang
    sudo apt-get install libclang-dev
  else
    echo installing llvm from brew
    brew install llvm
  fi

script:
- (cd onig && cargo build --no-default-features --verbose)
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]
  then
    p=$(cd ./target/debug/build/onig_sys-*/out/lib/ && pwd)
    echo "adding $p to linker path"
    export LD_LIBRARY_PATH="${p}:${LD_LIBRARY_PATH}"
  fi
- (cd onig && cargo test --no-default-features --verbose)
- (cd onig_sys && cargo test --no-default-features --verbose)
- (cd onig && cargo build --features="$ONIG_FEATURES" --verbose)
- (cd onig && cargo test --features="$ONIG_FEATURES" --verbose)
- (cd onig_sys && cargo test --features="$ONIG_FEATURES" --verbose)

# Allow failures in the nightly build. We don't want to fail just
# because of Rust instability.
matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      os: osx
      env: RUSTONIG_STATIC_LIBONIG=1
      compiler: clang
    - rust: stable
      os: linux
      env: RUSTONIG_STATIC_LIBONIG=1
    - rust: nightly
      os: linux
      env: ONIG_FEATURES=std-pattern
    - rust: nightly
      os: osx
      env: ONIG_FEATURES=std-pattern
      compiler: clang
