[package]
name = "onig"
version = "1.3.0"
authors = [
        "Will Speak <will@willspeak.me>",
        "Ivan Ivashchenko <defuz@me.com>"
]

description = """Rust-Onig is a set of rust bindings for the
            oniguruma regular expression library."""
repository = "http://github.com/iwillspeak/rust-onig"
documentation = "http://rust-onig.github.io/rust-onig/onig/"
readme = "README.md"
license = "MIT"

[features]
std-pattern = []
static-libonig = ["onig_sys/static_onig"]

[dependencies]
libc = "0.2"
bitflags = "0.7"
lazy_static = "0.2"

[target.'cfg(not(target_env = "musl"))'.dependencies.onig_sys]
version = "63.0.2"
path = "onig_sys"

[target.'cfg(target_env = "musl")'.dependencies.onig_sys]
features = [ "static_onig"]
version = "63.0.2"
path = "onig_sys"
