[package]
name = "onig_sys"
version = "0.4.0"
authors = ["Will Speak <will@willspeak.me>", "Ivan Ivashchenko <defuz@me.com>"]
build = "build.rs"
links = "onig"

description = """The Onig Sys crate contains raw rust bindings to the
oniguruma library. This crate exposes a set of unsafe functions which
can then be used by other craetes to create safe wrappers around
Oniguruma.

You probably don't want to link to this crate directly."""

repository = "http://github.com/iwillspeak/rust-onig"
documentation = "http://rust-onig.github.io/rust-onig/onig_sys/"
readme = "../README.md"
license = "MIT"

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"
